[package]
name = "benchmarks"
version = "0.1.0"
edition = "2024"

[dependencies]
eframe = { version = "0.33.0", features = ["wgpu"] }
nix = { version = "0.30.1", features = ["feature"] }
rand = { version = "0.9.2", default-features = false, features = ["thread_rng"] }
seq-macro = "0.3.6"
sizef = "0.2.1"
winit = "0.30.12"
